### ISSUE TITLE
can't read @ConfigProperty

### ISSUE THREAD

**Issue by yurake** [yurake/k8s-3tier-webapp#1]
```
git/k8s-3tier-webapp-minikube/application/redis-mysql-quarkus
% ./mvnw compile quarkus:dev


[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< org.acme:redis-mysql-quarkus >--------------------
[INFO] Building redis-mysql-quarkus 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ redis-mysql-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ redis-mysql-quarkus ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- quarkus-maven-plugin:1.0.1.Final:dev (default-cli) @ redis-mysql-quarkus ---
Listening for transport dt_socket at address: 5005
The application is starting...
2019-12-20 17:17:49,727 INFO  [io.quarkus] (main) Quarkus 1.0.1.Final started in 0.956s. Listening on: http://0.0.0.0:8080
2019-12-20 17:17:49,785 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2019-12-20 17:17:49,785 INFO  [io.quarkus] (main) Installed features: [cdi, jdbc-mysql, resteasy]
java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
	at redis.clients.jedis.Connection.connect(Connection.java:181)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:100)
	at redis.clients.jedis.Connection.setTimeoutInfinite(Connection.java:93)
	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2787)
	at org.acme.service.RedisService.subscribeRedis(RedisService.java:39)
	at org.acme.events.TaskExecute.run(TaskExecute.java:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
the application is stopping...
```

**Comment by yurake** [comment]
Quarkus provided Programmatically access the configuration.
see: [config](https://quarkus.io/guides/config#programmatically-access-the-configuration)
