### ISSUE TITLE
[scheduled-quarkus]IllegalArgumentException: Unable to determine the proper baseUrl/baseUri

### ISSUE THREAD

**Issue by yurake** [yurake/k8s-3tier-webapp#109]
### Logs
```bash
23:14:29 ERROR [io.qu.sc.ru.SimpleScheduler] (executor-thread-1) Error occured while executing task for trigger IntervalTrigger [id=0_webapp.tier.schedule.CallRandomPublshSchedule_ScheduledInvoker_callDeleteDbs_992d682e03fadfd70e19a73459aaf60caaa58667, interval=600000]: java.lang.RuntimeException: Error injecting webapp.tier.resource.MongodbResource webapp.tier.schedule.CallRandomPublshSchedule.mongodbrsc
	at webapp.tier.schedule.CallRandomPublshSchedule_Bean.create(CallRandomPublshSchedule_Bean.zig:363)
	at webapp.tier.schedule.CallRandomPublshSchedule_Bean.create(CallRandomPublshSchedule_Bean.zig:52)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at webapp.tier.schedule.CallRandomPublshSchedule_ClientProxy.arc$delegate(CallRandomPublshSchedule_ClientProxy.zig:95)
	at webapp.tier.schedule.CallRandomPublshSchedule_ClientProxy.callDeleteDbs(CallRandomPublshSchedule_ClientProxy.zig:217)
	at webapp.tier.schedule.CallRandomPublshSchedule_ScheduledInvoker_callDeleteDbs_992d682e03fadfd70e19a73459aaf60caaa58667.invokeBean(CallRandomPublshSchedule_ScheduledInvoker_callDeleteDbs_992d682e03fadfd70e19a73459aaf60caaa58667.zig:45)
	at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
	at io.quarkus.scheduler.runtime.SimpleScheduler$2.run(SimpleScheduler.java:126)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.IllegalArgumentException: Unable to determine the proper baseUrl/baseUri. Consider registering using @RegisterRestClient(baseUri="someuri"), @RegisterRestClient(configKey="orkey"), or by adding 'mongodb/mp-rest/url' or 'mongodb/mp-rest/uri' to your Quarkus configuration
	at io.quarkus.restclient.runtime.RestClientBase.configureBaseUrl(RestClientBase.java:188)
	at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:49)
	at webapp.tier.resource.MongodbResource_4bf630b888b81e4e2d7b197ec4fc6bdee01c30d0_Synthetic_Bean.create(MongodbResource_4bf630b888b81e4e2d7b197ec4fc6bdee01c30d0_Synthetic_Bean.zig:237)
	at webapp.tier.resource.MongodbResource_4bf630b888b81e4e2d7b197ec4fc6bdee01c30d0_Synthetic_Bean.get(MongodbResource_4bf630b888b81e4e2d7b197ec4fc6bdee01c30d0_Synthetic_Bean.zig:41)
	at webapp.tier.resource.MongodbResource_4bf630b888b81e4e2d7b197ec4fc6bdee01c30d0_Synthetic_Bean.get(MongodbResource_4bf630b888b81e4e2d7b197ec4fc6bdee01c30d0_Synthetic_Bean.zig:76)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:53)
	at webapp.tier.schedule.CallRandomPublshSchedule_Bean.create(CallRandomPublshSchedule_Bean.zig:346)
	... 21 more

23:14:29 ERROR [io.qu.sc.ru.SimpleScheduler] (executor-thread-2) Error occured while executing task for trigger IntervalTrigger [id=1_webapp.tier.schedule.CallRandomPublshSchedule_ScheduledInvoker_callRandomPublsh_6039ec9d426ab943aefcf82c79961d32a42f4740, interval=10000]: java.lang.RuntimeException: Error injecting webapp.tier.resource.MongodbResource webapp.tier.schedule.CallRandomPublshSchedule.mongodbrsc
	at webapp.tier.schedule.CallRandomPublshSchedule_Bean.create(CallRandomPublshSchedule_Bean.zig:363)
	at webapp.tier.schedule.CallRandomPublshSchedule_Bean.create(CallRandomPublshSchedule_Bean.zig:52)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at webapp.tier.schedule.CallRandomPublshSchedule_ClientProxy.arc$delegate(CallRandomPublshSchedule_ClientProxy.zig:95)
	at webapp.tier.schedule.CallRandomPublshSchedule_ClientProxy.callRandomPublsh(CallRandomPublshSchedule_ClientProxy.zig:155)
	at webapp.tier.schedule.CallRandomPublshSchedule_ScheduledInvoker_callRandomPublsh_6039ec9d426ab943aefcf82c79961d32a42f4740.invokeBean(CallRandomPublshSchedule_ScheduledInvoker_callRandomPublsh_6039ec9d426ab943aefcf82c79961d32a42f4740.zig:45)
	at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
	at io.quarkus.scheduler.runtime.SimpleScheduler$2.run(SimpleScheduler.java:126)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1411)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.IllegalArgumentException: Unable to determine the proper baseUrl/baseUri. Consider registering using @RegisterRestClient(baseUri="someuri"), @RegisterRestClient(configKey="orkey"), or by adding 'mongodb/mp-rest/url' or 'mongodb/mp-rest/uri' to your Quarkus configuration
	at io.quarkus.restclient.runtime.RestClientBase.configureBaseUrl(RestClientBase.java:188)
	at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:49)
	at webapp.tier.resource.MongodbResource_4bf630b888b81e4e2d7b197ec4fc6bdee01c30d0_Synthetic_Bean.create(MongodbResource_4bf630b888b81e4e2d7b197ec4fc6bdee01c30d0_Synthetic_Bean.zig:237)
	at webapp.tier.resource.MongodbResource_4bf630b888b81e4e2d7b197ec4fc6bdee01c30d0_Synthetic_Bean.get(MongodbResource_4bf630b888b81e4e2d7b197ec4fc6bdee01c30d0_Synthetic_Bean.zig:41)
	at webapp.tier.resource.MongodbResource_4bf630b888b81e4e2d7b197ec4fc6bdee01c30d0_Synthetic_Bean.get(MongodbResource_4bf630b888b81e4e2d7b197ec4fc6bdee01c30d0_Synthetic_Bean.zig:76)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:53)
	at webapp.tier.schedule.CallRandomPublshSchedule_Bean.create(CallRandomPublshSchedule_Bean.zig:346)
	... 21 more
```

**Comment by yurake** [comment]
fix.
