### ISSUE TITLE
[rabbitmq-mysql-quarkus] Channel Close Error.: com.rabbitmq.client.AlreadyClosedException

### ISSUE THREAD

**Issue by yurake** [yurake/k8s-3tier-webapp#113]
### Logs
```bash
21:58:20 SEVERE [RabbitMqService] (pool-3-thread-1) Channel Close Error.: com.rabbitmq.client.AlreadyClosedException: connection is already closed due to clean connection shutdown; protocol method: #method<connection.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.processShutdownSignal(AMQChannel.java:350)
	at com.rabbitmq.client.impl.ChannelN.startProcessShutdownSignal(ChannelN.java:286)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:612)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:546)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:539)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.close(AutorecoveringChannel.java:73)
	at webapp.tier.service.RabbitMqService.closeChannel(RabbitMqService.java:73)
	at webapp.tier.service.RabbitMqService.run(RabbitMqService.java:112)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by yurake** [comment]
fix with #112
