### ISSUE TITLE
[jaxrs-postgres-quarkus] PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by yurake** [yurake/k8s-3tier-webapp#114]
### Logs
```bash
14:30:58 WARNING [ReadinessHealthCheck] (vert.x-worker-thread-8) Readiness: DOWN
14:31:01 SEVERE [DbService] (vert.x-worker-thread-10) Status Check Error.: org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2578)
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2690)
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:156)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:255)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:459)
	at org.postgresql.Driver.connect(Driver.java:261)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at webapp.tier.service.DbService.getConnection(DbService.java:27)
	at webapp.tier.service.DbService.connectionStatus(DbService.java:32)
	at webapp.tier.service.PostgresService.connectionStatus(PostgresService.java:32)
	at webapp.tier.healthcheck.ReadinessHealthCheck.call(ReadinessHealthCheck.java:24)
	at webapp.tier.healthcheck.ReadinessHealthCheck_ClientProxy.call(ReadinessHealthCheck_ClientProxy.zig:36)
	at io.smallrye.health.SmallRyeHealthReporter.jsonObject(SmallRyeHealthReporter.java:185)
	at io.smallrye.health.SmallRyeHealthReporter.fillCheck(SmallRyeHealthReporter.java:172)
	at io.smallrye.health.SmallRyeHealthReporter.processChecks(SmallRyeHealthReporter.java:160)
	at io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:138)
	at io.smallrye.health.SmallRyeHealthReporter.getReadiness(SmallRyeHealthReporter.java:105)
	at io.smallrye.health.SmallRyeHealthReporter_ClientProxy.getReadiness(SmallRyeHealthReporter_ClientProxy.zig:101)
	at io.quarkus.smallrye.health.runtime.SmallRyeReadinessHandler.handle(SmallRyeReadinessHandler.java:42)
	at io.quarkus.smallrye.health.runtime.SmallRyeReadinessHandler.handle(SmallRyeReadinessHandler.java:34)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

**Comment by yurake** [comment]
```bash
postgres=# show max_connections;
 max_connections
-----------------
 100
(1 row)

postgres=# show tcp_keepalives_idle;
 tcp_keepalives_idle
---------------------
 0
(1 row)

postgres=# show tcp_keepalives_interval;
 tcp_keepalives_interval
-------------------------
 0
(1 row)

postgres=# show tcp_keepalives_count;
 tcp_keepalives_count
----------------------
 0
(1 row)
```

**Comment by yurake** [comment]
```bash
max_connections = 200			# (change requires restart)
tcp_keepalives_idle = 60		# TCP_KEEPIDLE, in seconds;
					# 0 selects the system default
tcp_keepalives_interval = 5		# TCP_KEEPINTVL, in seconds;
					# 0 selects the system default
tcp_keepalives_count = 6		# TCP_KEEPCNT;
					# 0 selects the system default
```

**Comment by yurake** [comment]
* add conf file for postgres default conf
https://github.com/yurake/k8s-3tier-webapp/blob/0c1f7507e75801182e7d47189fa942c5aeba129b/kubernetes/postgres/conf/postgresql.conf

* add CMD param in Dockerfile
https://www.postgresql.jp/document/9.1/html/config-setting.html
以下のようにpostgresコマンドに対してコマンドラインオプションとして与えます。
postgres -c log_connections=yes -c log_destination='syslog'

* add ENV param in Dockerfile
https://www.postgresql.org/docs/10/runtime-config-connection.html#RUNTIME-CONFIG-CONNECTION-SETTINGS
> tcp_keepalives_idle (integer)
> Specifies the number of seconds of inactivity after which TCP should send a keepalive message to the client. A value of 0 uses the system default. This parameter is supported only on systems that support TCP_KEEPIDLE or an equivalent socket option, and on Windows; on other systems, it must be zero. In sessions connected via a Unix-domain socket, this parameter is ignored and always reads as zero.

* add SET param in init.sql
https://www.postgresql.jp/document/9.1/html/config-setting.html
個別のSQLセッションのいくつかのパラメータはSETコマンドで変更可能です。例えば：
SET ENABLE_SEQSCAN TO OFF;

* add client URL param In apprication.properties
https://pgdash.io/blog/postgres-configuration-cheatsheet.html

**Comment by yurake** [comment]
http://docs.docker.jp/engine/reference/builder.html

**Comment by yurake** [comment]
* add conf file for postgres default conf
→ not working

* add CMD param in Dockerfile
→ not working

* add ENV param in Dockerfile
→ not working

* add SET param in init.sql
→ not try

* add client URL param In apprication.properties
→ not try

* use connection pool, related to #116
→ best solution

**Comment by yurake** [comment]
![image](https://user-images.githubusercontent.com/17479478/80171646-e01b0300-8625-11ea-83d8-93557f4304f6.png)
