### ISSUE TITLE
[wlp] NameNotFoundException

### ISSUE THREAD

**Issue by yurake** [yurake/k8s-3tier-webapp#1878]
### Logs
```bash
curl -v http://wlp.minikube/spring/mysql/select | jq
```
```bash
$ kubectl logs -f wlp-54f6cf4bf9-l6fsn

[err] javax.naming.NameNotFoundException: Intermediate context does not exist: jdbc/mysql
[err] 	at com.ibm.ws.jndi.internal.ContextNode.getTargetNode(ContextNode.java:125)
[err] 	at [internal classes]
[err] 	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
[err] 	at webapp.tier.db.MysqlService.getConnection(MysqlService.java:35)
[err] 	at webapp.tier.db.MysqlService.select(MysqlService.java:65)
[err] 	at webapp.controller.MysqlController.select(MysqlController.java:40)
[err] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[err] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[err] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[err] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[err] 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
[err] 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
[err] 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
[err] 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
[err] 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
[err] 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
[err] 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1061)
[err] 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:961)
[err] 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
[err] 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
[err] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
[err] 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
[err] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
[err] 	at [internal classes]
[err] 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
[err] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
[err] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
[err] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
[err] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[err] 	at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by yurake** [comment]
resolved in #1868
