### ISSUE TITLE
[implementer-grpc-quarkus] JUnit ERROR: Unable to start the gRPC server

### ISSUE THREAD

**Issue by yurake** [yurake/k8s-3tier-webapp#2276]
### Logs
```bash
ERROR: Unable to start the gRPC server
java.lang.ExceptionInInitializerError
	at io.quarkus.grpc.runtime.GrpcServerRecorder.buildServer(GrpcServerRecorder.java:340)
	at io.quarkus.grpc.runtime.GrpcServerRecorder.access$300(GrpcServerRecorder.java:63)
	at io.quarkus.grpc.runtime.GrpcServerRecorder$GrpcServerVerticle.start(GrpcServerRecorder.java:400)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: The LogManager was not properly installed (you must set the "java.util.logging.manager" system property to "org.jboss.logmanager.LogManager")
	at org.jboss.logmanager.Logger.getLogger(Logger.java:57)
	at io.quarkus.grpc.runtime.supports.RequestScopeHandlerInterceptor.<clinit>(RequestScopeHandlerInterceptor.java:20)
	... 13 more
```

**Comment by yurake** [comment]
Add jvm args
`-Djava.util.logging.manager=org.jboss.logmanager.LogManager"`
<img width="665" alt="スクリーンショット 2021-05-05 23 45 27" src="https://user-images.githubusercontent.com/17479478/117160421-0dcf8600-adfc-11eb-8f3d-17dc525587ca.png">
