### ISSUE TITLE
NoClassDefFoundError: org/apache/log4j/Logger

### ISSUE THREAD

**Issue by yurake** [yurake/k8s-3tier-webapp#27]
### Expected
no error

### Actual
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger

### Logs
```
$ kubectl logs -f hazelcast-mysql-quarkus-6945c7fdc8-ffpsc                                                           (git)-[master]
exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Duser.timezone=Asia/Tokyo -Dhazelcast.logging.type=log4j -javaagent:/opt/agent-bond/agent-bond.jar=jmx_exporter{{9779:/opt/agent-bond/jmx_exporter_config.yml}} -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
00:46:51 INFO  [AppLifecycleBean] (main) The application is starting...
Exception in thread "pool-4-thread-1" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at com.hazelcast.logging.Log4jFactory.createLogger(Log4jFactory.java:29)
	at com.hazelcast.logging.LoggerFactorySupport$1.createNew(LoggerFactorySupport.java:32)
	at com.hazelcast.logging.LoggerFactorySupport$1.createNew(LoggerFactorySupport.java:30)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:125)
	at com.hazelcast.logging.LoggerFactorySupport.getLogger(LoggerFactorySupport.java:38)
	at com.hazelcast.logging.Logger.getLogger(Logger.java:110)
	at com.hazelcast.logging.Logger.getLogger(Logger.java:64)
	at com.hazelcast.config.AbstractXmlConfigHelper.<clinit>(AbstractXmlConfigHelper.java:54)
	at webapp.tier.service.ConnectHazelcast.getInstance(ConnectHazelcast.java:35)
	at webapp.tier.service.HazelcastService.subscribeHazelcast(HazelcastService.java:38)
	at webapp.tier.events.TaskExecute.run(TaskExecute.java:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

**Comment by yurake** [comment]
same issue 

```
or id: cdd5a7c2-b30e-40d8-81f7-dc28c9c54c7e-1: java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at com.hazelcast.logging.Log4jFactory.createLogger(Log4jFactory.java:29)
	at com.hazelcast.logging.LoggerFactorySupport$1.createNew(LoggerFactorySupport.java:32)
	at com.hazelcast.logging.LoggerFactorySupport$1.createNew(LoggerFactorySupport.java:30)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:125)
	at com.hazelcast.logging.LoggerFactorySupport.getLogger(LoggerFactorySupport.java:38)
	at com.hazelcast.logging.Logger.getLogger(Logger.java:110)
	at com.hazelcast.logging.Logger.getLogger(Logger.java:64)
	at com.hazelcast.instance.BuildInfoProvider.<clinit>(BuildInfoProvider.java:43)
	at com.hazelcast.spi.properties.GroupProperty.<clinit>(GroupProperty.java:985)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.<init>(HazelcastClientInstanceImpl.java:221)
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:463)
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:421)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:138)
	at webapp.tier.service.ConnectHazelcast.getInstance(ConnectHazelcast.java:34)
	at webapp.tier.service.HazelcastCacheService.isActive(HazelcastCacheService.java:90)
	at webapp.tier.healthcheck.ReadinessHealthCheck.call(ReadinessHealthCheck.java:22)
	at webapp.tier.healthcheck.ReadinessHealthCheck_ClientProxy.call(ReadinessHealthCheck_ClientProxy.zig:36)
	at io.smallrye.health.SmallRyeHealthReporter.jsonObject(SmallRyeHealthReporter.java:154)
	at io.smallrye.health.SmallRyeHealthReporter.fillCheck(SmallRyeHealthReporter.java:141)
	at io.smallrye.health.SmallRyeHealthReporter.processChecks(SmallRyeHealthReporter.java:129)
	at io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:107)
	at io.smallrye.health.SmallRyeHealthReporter.getReadiness(SmallRyeHealthReporter.java:97)
	at io.smallrye.health.SmallRyeHealthReporter_ClientProxy.getReadiness(SmallRyeHealthReporter_ClientProxy.zig:101)
	at io.quarkus.smallrye.health.runtime.SmallRyeReadinessHandler.handle(SmallRyeReadinessHandler.java:40)
	at io.quarkus.smallrye.health.runtime.SmallRyeReadinessHandler.handle(SmallRyeReadinessHandler.java:32)
	at io.quarkus.vertx.http.runtime.ResumeHandler.handle(ResumeHandler.java:19)
	at io.quarkus.vertx.http.runtime.ResumeHandler.handle(ResumeHandler.java:6)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 34 more
```
