### ISSUE TITLE
[consumer-rabbitmq-quarkus] Expected an integer value, got "tcp://10.96.168.113:5672"

### ISSUE THREAD

**Issue by yurake** [yurake/k8s-3tier-webapp#2783]
### Logs
```bash
10:42:48 ERROR [io.sm.re.me.rabbitmq] (main) SRMSG17037: Unable to create client: java.lang.IllegalArgumentException: SRCFG00039: The config property rabbitmq-port with the config value "tcp://10.96.168.113:5672" threw an Exception whilst being converted SRCFG00029: Expected an integer value, got "tcp://10.96.168.113:5672"
	at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:280)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:238)
	at io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:337)
```

**Comment by yurake** [comment]
https://ja.quarkus.io/guides/rabbitmq-reference#rabbitmq-ブローカーアクセスの設定
https://ja.quarkus.io/guides/rabbitmq-dev-services

**Comment by yurake** [comment]
```bash
02:46:50 ERROR [io.ve.ra.im.RabbitMQClientImpl] (executor-thread-1) Could not connect to rabbitmq: java.io.IOException
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:129)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:125)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:147)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:439)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1139)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1087)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:985)
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.newConnection(RabbitMQClientImpl.java:152)
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.connect(RabbitMQClientImpl.java:830)
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.lambda$tryConnect$36(RabbitMQClientImpl.java:750)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.rabbitmq.client.ShutdownSignalException: connection error; protocol method: #method<connection.close>(reply-code=530, reply-text=NOT_ALLOWED - vhost / not found, class-id=10, method-id=40)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:293)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:141)
	... 18 more
```
