### ISSUE TITLE
[consumer-kafka-quarkus] WebApplicationException: Unknown error, status code 500

### ISSUE THREAD

**Issue by yurake** [yurake/k8s-3tier-webapp#2787]
### Logs
```bash
04:50:10 ERROR [io.sm.re.me.provider] (vert.x-eventloop-thread-0) SRMSG00200: The method webapp.tier.service.KafkaSubscribeService#process has thrown an exception: javax.ws.rs.WebApplicationException: Unknown error, status code 500
	at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:21)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:41)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:155)
	at jdk.proxy4.$Proxy272.random(Unknown Source)
	at webapp.tier.service.KafkaSubscribeService.process(KafkaSubscribeService.java:24)
	at webapp.tier.service.KafkaSubscribeService_ClientProxy.process(Unknown Source)
	at webapp.tier.service.KafkaSubscribeService_SmallRyeMessagingInvoker_process_bd386abe989418e778612ad8212523c81d813d5e.invoke(Unknown Source)
	at io.smallrye.reactive.messaging.providers.AbstractMediator.invoke(AbstractMediator.java:104)
	at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeOnMessageContext$1(AbstractMediator.java:112)
	at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$0(LocalContextMetadata.java:34)
	at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$1(LocalContextMetadata.java:53)
	at io.smallrye.reactive.messaging.providers.helpers.VertxContext.runOnContext(VertxContext.java:24)
	at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$2(LocalContextMetadata.java:51)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.request(UniToMultiPublisher.java:74)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onSubscribe(MultiFlatMapOp.java:601)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher.subscribe(UniToMultiPublisher.java:26)
	at io.smallrye.mutiny.groups.MultiCreate$1.subscribe(MultiCreate.java:163)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem(MultiFlatMapOp.java:193)
	at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:50)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:99)
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onItem(MultiOperatorProcessor.java:100)
	at io.smallrye.reactive.messaging.providers.locals.ContextDecorator$ContextMulti$ContextProcessor.lambda$onItem$1(ContextDecorator.java:84)
	at io.smallrye.reactive.messaging.providers.helpers.VertxContext.lambda$runOnContext$0(VertxContext.java:26)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
```

**Comment by yurake** [comment]
```bash
04:50:10 WARN  [or.ap.ka.cl.co.ConsumerConfig] (main) The configuration 'port[9092]tcp.addr' was supplied but isn't a known config.
04:50:10 WARN  [or.ap.ka.cl.co.ConsumerConfig] (main) The configuration 'service.port.port' was supplied but isn't a known config.
04:50:10 WARN  [or.ap.ka.cl.co.ConsumerConfig] (main) The configuration 'port[9092]tcp' was supplied but isn't a known config.
04:50:10 WARN  [or.ap.ka.cl.co.ConsumerConfig] (main) The configuration 'port.9092.tcp.addr' was supplied but isn't a known config.
04:50:10 WARN  [or.ap.ka.cl.co.ConsumerConfig] (main) The configuration 'port.9092.tcp.proto' was supplied but isn't a known config.
04:50:10 WARN  [or.ap.ka.cl.co.ConsumerConfig] (main) The configuration 'port.9092.tcp.port' was supplied but isn't a known config.
04:50:10 WARN  [or.ap.ka.cl.co.ConsumerConfig] (main) The configuration 'port' was supplied but isn't a known config.
04:50:10 WARN  [or.ap.ka.cl.co.ConsumerConfig] (main) The configuration 'port[9092]tcp.proto' was supplied but isn't a known config.
04:50:10 WARN  [or.ap.ka.cl.co.ConsumerConfig] (main) The configuration 'service.port' was supplied but isn't a known config.
04:50:10 WARN  [or.ap.ka.cl.co.ConsumerConfig] (main) The configuration 'port[9092]tcp.port' was supplied but isn't a known config.
04:50:10 WARN  [or.ap.ka.cl.co.ConsumerConfig] (main) The configuration 'port.9092.tcp' was supplied but isn't a known config.
04:50:10 WARN  [or.ap.ka.cl.co.ConsumerConfig] (main) The configuration 'service.host' was supplied but isn't a known config.
```

**Comment by yurake** [comment]
https://quarkus.io/guides/smallrye-fault-tolerance
